import type { WordEntry } from "./types.ts";

export const DEFAULT_WORDS: WordEntry[] = [
  { term: "corgi", definition: "Dog breed loved by the Royal Family." },
  { term: "apple", definition: "Fruit given to teachers by school children." },
  { term: "hamburger", definition: "Sandwich served at McDonald's." },
  { term: "minivan", definition: "Vehicle associated with families that have kids." },
  { term: "coffee", definition: "Warm beverage that helps tired people function." },
  { term: "yogurt", definition: "Cultured dairy product served at breakfast." },
  { term: "firefighter", definition: "Professional that rescues people from burning buildings." },
  { term: "banana", definition: "Fruit associated with monkeys and gorillas." },
  { term: "pillow", definition: "Something you rest your head on at night." },
  { term: "laptop", definition: "A portable computer." },
  { term: "television", definition: "Used to watch streaming video services while sitting on a couch." },
  { term: "mechanic", definition: "Profssional that fixes broken vehicles." },
  { term: "headphones", definition: "Used for listening to music." },
  { term: "sunglasses", definition: "Wear these to protect your vision." },
  { term: "sundress", definition: "Light outfit popular with women in the summer." },
  { term: "icecream", definition: "Frozen dessert popular with people during the summertime." },
  { term: "lawnmower", definition: "Used to cut grass." },
  { term: "widow", definition: "A woman whose husband has died." },
  { term: "ant", definition: "Small insect that lives in a colony." },
  { term: "cat", definition: "Raining ___ and dogs." },
  { term: "homework", definition: "Assigned by teachers for students to do at home." },
  { term: "bat", definition: "Sport equipment or animal that flies in the air." },
  { term: "raisins", definition: "Dried grapes." },
  { term: "orange", definition: "Citrus fruit." },
  { term: "battery", definition: "Stores electricity." },
  { term: "water", definition: "Hydrates plants." },
  { term: "barn", definition: "Holds livestock and is painted red." },
  { term: "elephant", definition: "Large animal with a trunk." },
  { term: "forest", definition: "Area with lots of trees." },
  { term: "river", definition: "Flowing with water." },
  { term: "loofa", definition: "Bathing apparatus." },
  { term: "mouse", definition: "Animal that squeaks." },
  { term: "foul", definition: "Violation; wrongdoing." },
  { term: "error", definition: "Unexpected negative event in computing." }
];
